<h1 align='center'> CS353 Machine Learning Lab</h1>
<h1 align='center'>K-Nearest Neighors (02/03/21)</h1>
<h2 align='center'>Keerti Chaudhary (181CO226)</h2>

# Task:
Perform KNN on a sample dataset.

## Social network ads dataset


This dataset is taken from kaggle 

(https://www.kaggle.com/rakeshrau/social-network-ads)

# Importing Libraries

In [157]:
import pandas as pd
import numpy as np
import sklearn.preprocessing as preprocessing
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix,accuracy_score, classification_report

# Loading dataset

In [158]:
df = pd.read_csv('Social_Network_Ads.csv')
print('\nThe shape of the dataset is', df.shape)
print('The first five tuples from the housing dataset are:')
df.head()


The shape of the dataset is (400, 5)
The first five tuples from the housing dataset are:


User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [159]:
df.describe()

User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000

In [160]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [161]:
X = df.iloc[:, [1, 2, 3]].values
y = df.iloc[:, -1].values
print(X.shape)
print(y.shape)

(400, 3)
(400,)


In [162]:
le = LabelEncoder()
X[:,0] = le.fit_transform(X[:,0])

# Splitting Data

We are using X-y split method with test size 20 % and random state 5.

In [163]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=25)

In [164]:
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(320, 3) (80, 3) (320,) (80,)


## Data preprocessing

In [165]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [166]:
X_test_s

array([[-0.36407386, -0.46788668,  2.01530984, ...,  0.23788767,
         0.29788544,  0.34519498],
       [ 0.22264871, -0.46788668,  0.91817139, ...,  0.85716832,
         0.3777139 ,  0.37163116],
       [-0.34579352, -0.46788668, -0.63961989, ...,  0.51937887,
         0.4216925 , -1.00616058],
       ...,
       [-0.37497386, -0.46788668, -1.12352334, ..., -1.16956836,
         0.36301962, -0.88175501],
       [-0.27832404, -0.46788668,  1.46892036, ...,  1.42015073,
        -0.9762434 ,  0.7339624 ],
       [-0.36980857, -0.46788668, -1.29209031, ..., -0.38139299,
         0.36885565, -0.1944142 ]])

# Implementing KNN Classifier


The k-nearest neighbors (KNN) algorithm is a simple, supervised machine learning algorithm that can be used to solve both classification and regression problems.

In [167]:
knn = KNeighborsClassifier(n_neighbors = 1)
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [168]:
y_test

array([0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0])

In [169]:
y_pred = knn.predict(X_test)
y_pred

array([1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Computing Accuracy

In [170]:
ac = accuracy_score(y_test, y_pred)
print(" Accuracy ")
ac

 Accuracy 


0.825

### Confusion Matrix

In [171]:
cm = confusion_matrix(y_test, y_pred)
print(" Confusion Matrix ")
cm

 Confusion Matrix 


array([[48,  5],
       [ 9, 18]])

In [172]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.84      0.91      0.87        53
           1       0.78      0.67      0.72        27

    accuracy                           0.82        80
   macro avg       0.81      0.79      0.80        80
weighted avg       0.82      0.82      0.82        80



## Trying different number of nearest neighbors

In [173]:
knn_2 = KNeighborsClassifier(n_neighbors = 2)
knn_2.fit(X_train, y_train)
y_pred_2 = knn_2.predict(X_test)
ac_2 = accuracy_score(y_test, y_pred_2)
print(" Accuracy ")
ac_2

 Accuracy 


0.825

In [174]:
knn_10 = KNeighborsClassifier(n_neighbors = 10)
knn_10.fit(X_train, y_train)
y_pred_10 = knn_10.predict(X_test)
ac_10 = accuracy_score(y_test, y_pred_10)
print(" Accuracy ")
ac_10

 Accuracy 


0.9375

In [175]:
knn_200 = KNeighborsClassifier(n_neighbors = 200)
knn_200.fit(X_train, y_train)
y_pred_200 = knn_20.predict(X_test)
ac_200 = accuracy_score(y_test, y_pred_200)
print(" Accuracy ")
ac_200

 Accuracy 


0.6625

## Choosing the best value of 'n' using GridSearchCV

In [176]:
params = {'n_neighbors': range(1,100)}
grid_search_cv = GridSearchCV(KNeighborsClassifier(), params)
grid_search_cv.fit(X_train, y_train)

GridSearchCV(cv=None, error_score=nan,
             estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                            metric='minkowski',
                                            metric_params=None, n_jobs=None,
                                            n_neighbors=5, p=2,
                                            weights='uniform'),
             iid='deprecated', n_jobs=None,
             param_grid={'n_neighbors': range(1, 100)}, pre_dispatch='2*n_jobs',
             refit=True, return_train_score=False, scoring=None, verbose=0)

In [177]:
grid_search_cv.best_params_

{'n_neighbors': 5}

In [178]:
optimised_KNN = grid_search_cv.best_estimator_
y_test_pred = optimised_KNN.predict(X_test) 

In [179]:
confusion_matrix(y_test, y_test_pred)

array([[50,  3],
       [ 2, 25]])

In [180]:
accuracy_score(y_test, y_test_pred)

0.9375

In [182]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.84      0.91      0.87        53
           1       0.78      0.67      0.72        27

    accuracy                           0.82        80
   macro avg       0.81      0.79      0.80        80
weighted avg       0.82      0.82      0.82        80

