<h1 align='center'> CS353 Machine Learning Lab</h1>
<h2 align='center'>Keerti Chaudhary (181CO226)</h2>

# NOR gate using Neural Network

# Loading Libraries

In [ ]:
import keras
from keras import models
from keras import layers
from keras import losses 
from keras import optimizers 
from keras import metrics 
import numpy as np
import pandas as pd

# Creating Dataset

In [ ]:
X = np.random.randint(0, 2, (10000, 2))
y=  (X[:,0] +  X[:,1])


In [ ]:
for i in range(len(y)):
  if y[i]==0:
    y[i]=1
  else:
    y[i]=0

In [ ]:
X

array([[0, 0],
       [1, 0],
       [1, 1],
       ...,
       [1, 0],
       [0, 1],
       [1, 0]])

In [ ]:
y

array([1, 0, 0, ..., 0, 0, 0])

In [ ]:
print(pd.DataFrame(X).describe())
print(pd.DataFrame(X).info())

                  0             1
count  10000.000000  10000.000000
mean       0.496300      0.498800
std        0.500011      0.500024
min        0.000000      0.000000
25%        0.000000      0.000000
50%        0.000000      0.000000
75%        1.000000      1.000000
max        1.000000      1.000000
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       10000 non-null  int64
 1   1       10000 non-null  int64
dtypes: int64(2)
memory usage: 156.4 KB
None


In [ ]:
print(pd.DataFrame(y).describe())
print(pd.DataFrame(y).info())

                  0
count  10000.000000
mean       0.254100
std        0.435376
min        0.000000
25%        0.000000
50%        0.000000
75%        1.000000
max        1.000000
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       10000 non-null  int64
dtypes: int64(1)
memory usage: 78.2 KB
None


# Splitting Dataset into Training and Testing

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y, test_size = 0.25, random_state = 0)

# Neural Network Model

In [ ]:
model = models.Sequential()
model.add(layers.Dense(1, input_shape=(2,), activation='sigmoid'))
model.compile(loss='mean_squared_error', optimizer='adam', metrics=[metrics.categorical_accuracy])

# Training

In [ ]:
result=history = model.fit(X_train, y_train, validation_split=(0.2), batch_size=100, epochs=32, verbose=1)

Epoch 1/32
60/60 [==============================] - 1s 9ms/step - loss: 0.1861 - categorical_accuracy: 1.0000 - val_loss: 0.1754 - val_categorical_accuracy: 1.0000
Epoch 2/32
60/60 [==============================] - 0s 2ms/step - loss: 0.1721 - categorical_accuracy: 1.0000 - val_loss: 0.1636 - val_categorical_accuracy: 1.0000
Epoch 3/32
60/60 [==============================] - 0s 2ms/step - loss: 0.1624 - categorical_accuracy: 1.0000 - val_loss: 0.1542 - val_categorical_accuracy: 1.0000
Epoch 4/32
60/60 [==============================] - 0s 2ms/step - loss: 0.1538 - categorical_accuracy: 1.0000 - val_loss: 0.1468 - val_categorical_accuracy: 1.0000
Epoch 5/32
60/60 [==============================] - 0s 2ms/step - loss: 0.1445 - categorical_accuracy: 1.0000 - val_loss: 0.1409 - val_categorical_accuracy: 1.0000
Epoch 6/32
60/60 [==============================] - 0s 2ms/step - loss: 0.1408 - categorical_accuracy: 1.0000 - val_loss: 0.1360 - val_categorical_accuracy: 1.0000
Epoch 7/32
60/60

# Evaluation

In [ ]:
final=model.evaluate(X_test,y_test)

79/79 [==============================] - 0s 1ms/step - loss: 0.0682 - categorical_accuracy: 1.0000


In [ ]:
model.predict([[0,0]]).round()

array([[1.]], dtype=float32)

In [ ]:
model.predict([[0,1]]).round()

array([[0.]], dtype=float32)

In [ ]:
model.predict([[1,0]]).round()

array([[0.]], dtype=float32)

In [ ]:
model.predict([[1,1]]).round()

array([[0.]], dtype=float32)

# Results

In [ ]:
y_pred=model.predict(X_test).round()
print(y_pred)

[[1.]
 [1.]
 [0.]
 ...
 [0.]
 [1.]
 [1.]]


In [ ]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score
# accuracy: (tp + tn) / (p + n)
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy: %f' % accuracy)
# precision tp / (tp + fp)
precision = precision_score(y_test, y_pred)
print('Precision: %f' % precision)
# recall: tp / (tp + fn)
recall = recall_score(y_test, y_pred)
print('Recall: %f' % recall)
# f1: 2 tp / (2 tp + fp + fn)
f1 = f1_score(y_test, y_pred)
print('F1 score: %f' % f1)

Accuracy: 1.000000
Precision: 1.000000
Recall: 1.000000
F1 score: 1.000000
