<h1 align='center'> CS353 Machine Learning Lab</h1>
<h2 align='center'>Keerti Chaudhary (181CO226)</h2>

# AND gate using Neural Network

# Loading Libraries

In [1]:
import keras
from keras import models
from keras import layers
from keras import losses 
from keras import optimizers 
from keras import metrics 
import numpy as np
import pandas as pd

# Creating Dataset

In [2]:
X = np.random.randint(0, 2, (10000, 2))
y = X[:,0]*X[:,1]

In [5]:
print(pd.DataFrame(X).describe())
print(pd.DataFrame(X).info())

                  0             1
count  10000.000000  10000.000000
mean       0.495400      0.496900
std        0.500004      0.500015
min        0.000000      0.000000
25%        0.000000      0.000000
50%        0.000000      0.000000
75%        1.000000      1.000000
max        1.000000      1.000000
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       10000 non-null  int64
 1   1       10000 non-null  int64
dtypes: int64(2)
memory usage: 156.4 KB
None


In [6]:
print(pd.DataFrame(y).describe())
print(pd.DataFrame(y).info())

                0
count  10000.0000
mean       0.2460
std        0.4307
min        0.0000
25%        0.0000
50%        0.0000
75%        0.0000
max        1.0000
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       10000 non-null  int64
dtypes: int64(1)
memory usage: 78.2 KB
None


# Splitting Dataset into Training and Testing

In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y, test_size = 0.25, random_state = 0)

# Neural Network Model

In [7]:
model = models.Sequential()
model.add(layers.Dense(1, input_shape=(2,), activation='sigmoid'))
model.compile(loss='mean_squared_error', optimizer='adam', metrics=[metrics.categorical_accuracy])

# Training

In [16]:
result=history = model.fit(X_train, y_train, validation_split=(0.2), batch_size=100, epochs=32, verbose=1)

Epoch 1/32
60/60 [==============================] - 0s 3ms/step - loss: 0.0908 - categorical_accuracy: 1.0000 - val_loss: 0.0888 - val_categorical_accuracy: 1.0000
Epoch 2/32
60/60 [==============================] - 0s 2ms/step - loss: 0.0891 - categorical_accuracy: 1.0000 - val_loss: 0.0871 - val_categorical_accuracy: 1.0000
Epoch 3/32
60/60 [==============================] - 0s 2ms/step - loss: 0.0874 - categorical_accuracy: 1.0000 - val_loss: 0.0855 - val_categorical_accuracy: 1.0000
Epoch 4/32
60/60 [==============================] - 0s 1ms/step - loss: 0.0858 - categorical_accuracy: 1.0000 - val_loss: 0.0838 - val_categorical_accuracy: 1.0000
Epoch 5/32
60/60 [==============================] - 0s 1ms/step - loss: 0.0842 - categorical_accuracy: 1.0000 - val_loss: 0.0823 - val_categorical_accuracy: 1.0000
Epoch 6/32
60/60 [==============================] - 0s 2ms/step - loss: 0.0826 - categorical_accuracy: 1.0000 - val_loss: 0.0807 - val_categorical_accuracy: 1.0000
Epoch 7/32
60/60

# Evaluation

In [17]:
final=model.evaluate(X_test,y_test)

79/79 [==============================] - 0s 1ms/step - loss: 0.0503 - categorical_accuracy: 1.0000


In [18]:
model.predict([[0,0]]).round()

array([[0.]], dtype=float32)

In [19]:
model.predict([[0,1]]).round()

array([[0.]], dtype=float32)

In [20]:
model.predict([[1,0]]).round()

array([[0.]], dtype=float32)

In [21]:
model.predict([[1,1]]).round()

array([[1.]], dtype=float32)

## Results

In [24]:
y_pred=model.predict(X_test).round()
print(y_pred)

[[0.]
 [0.]
 [1.]
 ...
 [1.]
 [1.]
 [1.]]


In [29]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score
# accuracy: (tp + tn) / (p + n)
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy: %f' % accuracy)
# precision tp / (tp + fp)
precision = precision_score(y_test, y_pred)
print('Precision: %f' % precision)
# recall: tp / (tp + fn)
recall = recall_score(y_test, y_pred)
print('Recall: %f' % recall)
# f1: 2 tp / (2 tp + fp + fn)
f1 = f1_score(y_test, y_pred)
print('F1 score: %f' % f1)

Accuracy: 1.000000
Precision: 1.000000
Recall: 1.000000
F1 score: 1.000000
